site_name: wiki-ICM
site_url: https://github.com/wiki-ICM/wiki-ICM-web.git


nav:
  - Home: index.md
  - Primer Año : a1.md
  - Segundo Año : a2.md
  - Tercer Año : a3.md
  - Cuarto Año : a4.md
  - Quinto Año : a5.md
  - Sexto Año : a6.md
  - Electivos: elec.md 
  - Otros: ot.md
theme:
  name: material
  color_mode: auto
